# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import weatherdaily.models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdaily', '0002_weatherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherimage',
            name='weatherPic_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weatherimage',
            name='weatherPic_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherimage',
            name='weatherPic',
            field=models.ImageField(blank=True, height_field='weatherPic_height', null=True, upload_to=weatherdaily.models.upload_location, width_field='weatherPic_width'),
        ),
    ]
